`/forms/{formId}`へのPATCHとDELETEを実装する
GiganticMinecraft/seichi-api-schema pull request #35
Opened 2022-12-29 15:12 UTC by Lucky3028

2022-12-30 14:07 UTC, rito528 requested changes

2022-12-30 14:07 UTC, rito528 commented on schema/paths/forms/eachForm.yml
> +      description: データベースでエラー
> データベースでエラー

500番はデータベースエラーとは限らない気がします(他同様)

2022-12-30 14:08 UTC, Lucky3028 commented on schema/paths/forms/eachForm.yml
> +      description: データベースでエラー
素直に「サーバでエラー」で？

2022-12-31 03:31 UTC, rito528 commented on schema/paths/forms/eachForm.yml
> +      description: データベースでエラー
サーバーエラーで良いと思います

2023-01-02 11:12 UTC, rito528 approved these changes
LGTM.

2023-01-02 11:12 UTC, merged