フォームの一覧表示を追加
GiganticMinecraft/seichi-api-schema pull request #4
Opened 2022-12-06 11:46 UTC by Lucky3028

ほかリファクタリング

2022-12-06 11:52 UTC, Lucky3028 commented
blocks #3

2022-12-07 08:13 UTC, Lucky3028 commented
@rito528 requested for the review

2022-12-09 07:28 UTC, rito528 requested changes

2022-12-09 07:28 UTC, rito528 commented on schema/types/form.yaml
> +params:
formの定義はformsパッケージの中で行われて良いと思います。

2022-12-09 07:51 UTC, Lucky3028 commented on schema/types/form.yaml
> +params:
これディレクトリは一緒でいいというレベルの話で、ファイルごといっしょであるべきってことではないですよね？

2022-12-09 07:51 UTC, rito528 commented on schema/types/form.yaml
> +params:
そうですね

2022-12-09 08:16 UTC, rito528 approved these changes

2022-12-09 08:16 UTC, merged